-- @noindex
-- Renders a sampler matrix to SFZ and Decent Sampler presets.
-- Runs standalone under `lua preset.lua`.
--
-- A matrix is an array of groups, each:
--   { name = "Kick", note = 36, samples = {
--       { file = "Samples/Kick_v1_rr1.wav", lovel = 1, hivel = 31, seq = 1, seqlen = 5 },
--       ... } }
-- One group is one articulation on one MIDI note. lovel/hivel are the velocity
-- layer; seq/seqlen are the round robin position and cycle length.

local M = {}

----------------------------------------------------------------------
-- naming -- pure, and shared by the sampler action
----------------------------------------------------------------------

-- Filenames must survive being a path component and an XML attribute.
function M.slug(s)
  return (s:gsub("[^%w%-]+", "_"):gsub("^_+", ""):gsub("_+$", ""))
end

-- Slugs for a list of names, made unique. "Tap & Slap" and "Tap / Slap" both
-- reduce to Tap_Slap on their own, and two articulations pointing at the same
-- .wav means one silently overwrites the other's samples.
function M.slugs(names)
  local out, seen = {}, {}
  for i, raw in ipairs(names) do
    local base = M.slug(raw)
    if base == "" then base = ("group_%d"):format(i) end
    local s, k = base, 1
    while seen[s] do
      k = k + 1
      s = ("%s_%d"):format(base, k)
    end
    seen[s] = true
    out[i] = s
  end
  return out
end

-- Track name -> articulation name and MIDI note. "Kick [36]" pins the note.
-- A pin outside 0..127 is not a MIDI note: fall back rather than write key=128
-- into the preset, which no sampler will load.
function M.parse_name(raw, fallback_note, default_name)
  local note = tonumber(raw:match("%[(%d+)%]") or "")
  local name = raw:gsub("%s*%[%d+%]%s*$", "")
  if not note or note < 0 or note > 127 or note % 1 ~= 0 then note = fallback_note end
  if name == "" then name = default_name end
  return name, note
end

----------------------------------------------------------------------
-- SFZ -- the open format. Plain text, read by sfizz, LinuxSampler,
-- liquidsfz, OpenMPT, Bitwig, HISE. This is the archival copy.
----------------------------------------------------------------------

function M.build_sfz(matrix, kit)
  local out = {
    ("// %s"):format(kit),
    "// Generated by ReapeZoom -- https://github.com/berlogabob/ReapeZoom",
    "",
    "<control>",
    "default_path=",
    "",
    "<global>",
    "loop_mode=one_shot", -- play to the end, ignore note-off: correct for drums
    "ampeg_release=0.5",
    "",
  }
  for _, g in ipairs(matrix) do
    out[#out + 1] = ("// %s"):format(g.name)
    out[#out + 1] = ("<group> key=%d"):format(g.note)
    for _, s in ipairs(g.samples) do
      out[#out + 1] = ("<region> sample=%s lovel=%d hivel=%d seq_length=%d seq_position=%d")
        :format(s.file:gsub("/", "/"), s.lovel, s.hivel, s.seqlen, s.seq)
    end
    out[#out + 1] = ""
  end
  return table.concat(out, "\n")
end

----------------------------------------------------------------------
-- Decent Sampler -- the convenient format. Free player, closed source,
-- so it is the copy you play rather than the copy you keep.
----------------------------------------------------------------------

local function xml_escape(s)
  return (s:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;"))
end

-- XML comments may not contain "--" anywhere, nor end with "-". A kit name is
-- user text, so it has to be scrubbed or the whole preset fails to parse.
-- Exported so the trailing-hyphen rule can be tested directly: build_dspreset
-- always appends " : generated by ReapeZoom " after the name, so through that
-- path the body never ends at the name and the rule is unreachable.
function M.xml_comment(s)
  return (s:gsub("%-%-+", "-"):gsub("%-$", ""))
end
local xml_comment = M.xml_comment

function M.build_dspreset(matrix, kit)
  local out = {
    '<?xml version="1.0" encoding="UTF-8"?>',
    ('<DecentSampler minVersion="1.0.0">'),
    ("  <!-- %s : generated by ReapeZoom -->"):format(xml_comment(xml_escape(kit))),
    "  <groups>",
  }
  for _, g in ipairs(matrix) do
    out[#out + 1] = ('    <group name="%s">'):format(xml_escape(g.name))
    for _, s in ipairs(g.samples) do
      -- loNote/hiNote pinned to rootNote so a drum is not stretched across the keyboard
      out[#out + 1] = ('      <sample path="%s" rootNote="%d" loNote="%d" hiNote="%d"' ..
        ' loVel="%d" hiVel="%d" seqMode="round_robin" seqPosition="%d" seqLength="%d"/>')
        :format(xml_escape(s.file), g.note, g.note, g.note, s.lovel, s.hivel, s.seq, s.seqlen)
    end
    out[#out + 1] = "    </group>"
  end
  out[#out + 1] = "  </groups>"
  out[#out + 1] = "</DecentSampler>"
  return table.concat(out, "\n")
end

----------------------------------------------------------------------
-- self-check
----------------------------------------------------------------------

function M.selftest()
  local matrix = {
    { name = "Kick", note = 36, samples = {
      { file = "Samples/Kick_v1_rr1.wav", lovel = 1, hivel = 63, seq = 1, seqlen = 2 },
      { file = "Samples/Kick_v1_rr2.wav", lovel = 1, hivel = 63, seq = 2, seqlen = 2 },
      { file = "Samples/Kick_v2_rr1.wav", lovel = 64, hivel = 127, seq = 1, seqlen = 1 },
    } },
    { name = "Tap & Slap", note = 37, samples = {
      { file = "Samples/Tap _ Slap_v1_rr1.wav", lovel = 1, hivel = 127, seq = 1, seqlen = 1 },
    } },
  }

  local sfz = M.build_sfz(matrix, "Cajon")
  assert(sfz:find("loop_mode=one_shot", 1, true), "sfz must set one_shot")
  assert(sfz:find("<group> key=36", 1, true), "sfz group key")
  assert(sfz:find("sample=Samples/Kick_v1_rr2.wav lovel=1 hivel=63 seq_length=2 seq_position=2", 1, true),
    "sfz region line")
  assert(sfz:find("<group> key=37", 1, true), "second sfz group")

  -- a name with "--" in it must not produce an illegal XML comment
  local ds = M.build_dspreset(matrix, "Cajon -- v2")
  for body in ds:gmatch("<!%-%-(.-)%-%->") do
    assert(not body:find("%-%-"), ("illegal '--' inside XML comment: %q"):format(body))
    assert(not body:find("%-$"), ("XML comment ends with '-': %q"):format(body))
  end

  ds = M.build_dspreset(matrix, "Cajon")
  assert(ds:find('rootNote="36" loNote="36" hiNote="36"', 1, true), "ds note pinning")
  assert(ds:find('seqMode="round_robin" seqPosition="2" seqLength="2"', 1, true), "ds round robin")
  assert(ds:find('name="Tap &amp; Slap"', 1, true), "ds must escape ampersands")
  assert(not ds:find('name="Tap & Slap"', 1, true), "raw ampersand leaked into xml")
  local _, opens = ds:gsub("<group ", "")
  local _, closes = ds:gsub("</group>", "")
  assert(opens == closes and opens == 2, ("group tags unbalanced: %d/%d"):format(opens, closes))

  -- every escaped character, not just the ampersand: a raw < or " in an
  -- attribute is malformed XML and the preset will not load
  local nasty = {
    { name = 'A <b> & "c"', note = 40, samples = {
      { file = 'Samples/A_<b>_&_"c".wav', lovel = 1, hivel = 127, seq = 1, seqlen = 1 },
    } },
  }
  local nd = M.build_dspreset(nasty, "Kit")
  assert(nd:find("&lt;b&gt;", 1, true), "< and > must be escaped")
  assert(nd:find("&quot;c&quot;", 1, true), 'the " must be escaped')
  assert(nd:find("A &lt;b&gt; &amp; &quot;c&quot;", 1, true), "all escapes together")
  for attr in nd:gmatch('=%b""') do
    assert(not attr:sub(2, -2):find("[<>]"), ("raw angle bracket in attribute: %s"):format(attr))
  end

  -- Both XML comment rules, tested on the scrubber directly. Going through
  -- build_dspreset cannot reach the trailing-hyphen rule, because the generated
  -- comment always continues past the kit name.
  assert(M.xml_comment("Cajon-") == "Cajon", "a trailing hyphen must be removed")
  assert(M.xml_comment("Cajon--") == "Cajon", "trailing hyphens must be removed")
  assert(M.xml_comment("a -- b") == "a - b", "double hyphens must be collapsed")
  assert(M.xml_comment("a --- b") == "a - b", "long hyphen runs must be collapsed")
  assert(M.xml_comment("Cajon") == "Cajon", "a clean name must pass through")

  -- slugs ------------------------------------------------------------
  assert(M.slug("Tap & Slap") == "Tap_Slap", "slug of 'Tap & Slap'")
  assert(M.slug("  __Rim__  ") == "Rim", "slug must trim underscores")

  -- the collision that aliases two articulations onto one .wav
  local s = M.slugs { "Tap & Slap", "Tap / Slap", "Tap + Slap" }
  assert(s[1] ~= s[2] and s[2] ~= s[3] and s[1] ~= s[3],
    ("colliding names produced duplicate slugs: %s %s %s"):format(s[1], s[2], s[3]))
  assert(s[1] == "Tap_Slap", "the first collision keeps the plain slug")

  -- names that sanitise to nothing must still be distinct
  local empty = M.slugs { "&&&", "///" }
  assert(empty[1] ~= "" and empty[2] ~= "" and empty[1] ~= empty[2],
    ("all-invalid names produced %q and %q"):format(empty[1], empty[2]))

  -- parse_name --------------------------------------------------------
  local nm, nt = M.parse_name("Kick [36]", 35, "Track 1")
  assert(nm == "Kick" and nt == 36, ("parse_name gave %q, %s"):format(nm, tostring(nt)))
  nm, nt = M.parse_name("Snare", 38, "Track 3")
  assert(nm == "Snare" and nt == 38, "no pin must use the fallback note")
  nm, nt = M.parse_name("[40]", 35, "Track 1")
  assert(nm == "Track 1" and nt == 40, "a blank name must take the default")
  -- out of MIDI range: fall back rather than emit an unloadable key
  local _, over = M.parse_name("Kick [128]", 36, "Track 1")
  assert(over == 36, ("note 128 was accepted, got %d"):format(over))
  local _, way = M.parse_name("Kick [9999]", 36, "Track 1")
  assert(way == 36, ("note 9999 was accepted, got %d"):format(way))

  return true
end

if not reaper then
  assert(M.selftest())
  print("ok")
end

return M
