-- @noindex
-- Renders a sampler matrix to SFZ and Decent Sampler presets.
-- Runs standalone under `lua preset.lua`.
--
-- A matrix is an array of groups, each:
--   { name = "Kick", note = 36, samples = {
--       { file = "Samples/Kick_v1_rr1.wav", lovel = 1, hivel = 31, seq = 1, seqlen = 5 },
--       ... } }
-- One group is one articulation on one MIDI note. lovel/hivel are the velocity
-- layer; seq/seqlen are the round robin position and cycle length.

local M = {}

----------------------------------------------------------------------
-- SFZ -- the open format. Plain text, read by sfizz, LinuxSampler,
-- liquidsfz, OpenMPT, Bitwig, HISE. This is the archival copy.
----------------------------------------------------------------------

function M.build_sfz(matrix, kit)
  local out = {
    ("// %s"):format(kit),
    "// Generated by ReapeZoom -- https://github.com/berlogabob/ReapeZoom",
    "",
    "<control>",
    "default_path=",
    "",
    "<global>",
    "loop_mode=one_shot", -- play to the end, ignore note-off: correct for drums
    "ampeg_release=0.5",
    "",
  }
  for _, g in ipairs(matrix) do
    out[#out + 1] = ("// %s"):format(g.name)
    out[#out + 1] = ("<group> key=%d"):format(g.note)
    for _, s in ipairs(g.samples) do
      out[#out + 1] = ("<region> sample=%s lovel=%d hivel=%d seq_length=%d seq_position=%d")
        :format(s.file:gsub("/", "/"), s.lovel, s.hivel, s.seqlen, s.seq)
    end
    out[#out + 1] = ""
  end
  return table.concat(out, "\n")
end

----------------------------------------------------------------------
-- Decent Sampler -- the convenient format. Free player, closed source,
-- so it is the copy you play rather than the copy you keep.
----------------------------------------------------------------------

local function xml_escape(s)
  return (s:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;"))
end

-- XML comments may not contain "--" anywhere, nor end with "-". A kit name is
-- user text, so it has to be scrubbed or the whole preset fails to parse.
local function xml_comment(s)
  return (s:gsub("%-%-+", "-"):gsub("%-$", ""))
end

function M.build_dspreset(matrix, kit)
  local out = {
    '<?xml version="1.0" encoding="UTF-8"?>',
    ('<DecentSampler minVersion="1.0.0">'),
    ("  <!-- %s : generated by ReapeZoom -->"):format(xml_comment(xml_escape(kit))),
    "  <groups>",
  }
  for _, g in ipairs(matrix) do
    out[#out + 1] = ('    <group name="%s">'):format(xml_escape(g.name))
    for _, s in ipairs(g.samples) do
      -- loNote/hiNote pinned to rootNote so a drum is not stretched across the keyboard
      out[#out + 1] = ('      <sample path="%s" rootNote="%d" loNote="%d" hiNote="%d"' ..
        ' loVel="%d" hiVel="%d" seqMode="round_robin" seqPosition="%d" seqLength="%d"/>')
        :format(xml_escape(s.file), g.note, g.note, g.note, s.lovel, s.hivel, s.seq, s.seqlen)
    end
    out[#out + 1] = "    </group>"
  end
  out[#out + 1] = "  </groups>"
  out[#out + 1] = "</DecentSampler>"
  return table.concat(out, "\n")
end

----------------------------------------------------------------------
-- self-check
----------------------------------------------------------------------

function M.selftest()
  local matrix = {
    { name = "Kick", note = 36, samples = {
      { file = "Samples/Kick_v1_rr1.wav", lovel = 1, hivel = 63, seq = 1, seqlen = 2 },
      { file = "Samples/Kick_v1_rr2.wav", lovel = 1, hivel = 63, seq = 2, seqlen = 2 },
      { file = "Samples/Kick_v2_rr1.wav", lovel = 64, hivel = 127, seq = 1, seqlen = 1 },
    } },
    { name = "Tap & Slap", note = 37, samples = {
      { file = "Samples/Tap _ Slap_v1_rr1.wav", lovel = 1, hivel = 127, seq = 1, seqlen = 1 },
    } },
  }

  local sfz = M.build_sfz(matrix, "Cajon")
  assert(sfz:find("loop_mode=one_shot", 1, true), "sfz must set one_shot")
  assert(sfz:find("<group> key=36", 1, true), "sfz group key")
  assert(sfz:find("sample=Samples/Kick_v1_rr2.wav lovel=1 hivel=63 seq_length=2 seq_position=2", 1, true),
    "sfz region line")
  assert(sfz:find("<group> key=37", 1, true), "second sfz group")

  -- a name with "--" in it must not produce an illegal XML comment
  local ds = M.build_dspreset(matrix, "Cajon -- v2")
  for body in ds:gmatch("<!%-%-(.-)%-%->") do
    assert(not body:find("%-%-"), ("illegal '--' inside XML comment: %q"):format(body))
    assert(not body:find("%-$"), ("XML comment ends with '-': %q"):format(body))
  end

  ds = M.build_dspreset(matrix, "Cajon")
  assert(ds:find('rootNote="36" loNote="36" hiNote="36"', 1, true), "ds note pinning")
  assert(ds:find('seqMode="round_robin" seqPosition="2" seqLength="2"', 1, true), "ds round robin")
  assert(ds:find('name="Tap &amp; Slap"', 1, true), "ds must escape ampersands")
  assert(not ds:find('name="Tap & Slap"', 1, true), "raw ampersand leaked into xml")
  local _, opens = ds:gsub("<group ", "")
  local _, closes = ds:gsub("</group>", "")
  assert(opens == closes and opens == 2, ("group tags unbalanced: %d/%d"):format(opens, closes))

  return true
end

if not reaper then
  assert(M.selftest())
  print("ok")
end

return M
